version: '3.8'

services:
  flask-app:
    build: ./flask
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/app
    environment:
      - FLASK_ENV=development
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]

  django-app:
    build: ./django
    ports:
      - "8000:8000"
    volumes:
      - ./django:/app
    environment:
      - DJANGO_SETTINGS_MODULE=myapp.settings
